# Generated by Django 5.1.3 on 2024-11-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistrySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Reaching Lives Across The Country', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='ministry_section/')),
            ],
            options={
                'verbose_name': 'Ministry Section',
                'verbose_name_plural': 'Ministry Sections',
            },
        ),
    ]
