# Generated by Django 5.1.3 on 2024-11-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ministrysection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='people_description',
            field=models.TextField(default='People have accepted the salvation gospel to receive Christ through our outreach'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='reached_description',
            field=models.TextField(default='People have been reached with the gospel and have been discipled to walk with the professional love'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='villages_description',
            field=models.TextField(default='We have reached several villages so far. We continue to reach several villages with the gospel of Jesus'),
        ),
    ]
