# Generated by Django 5.1.3 on 2024-12-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='stat_desc1',
            field=models.CharField(default='An overview of the unreached people groups mostly in Nothern Nigeria', max_length=255),
        ),
        migrations.AddField(
            model_name='statistics',
            name='stat_desc2',
            field=models.CharField(default='Click on any colored state to see detailed statistics.', max_length=255),
        ),
        migrations.AddField(
            model_name='statistics',
            name='stat_title1',
            field=models.CharField(default='Our Statistics', max_length=255),
        ),
        migrations.AddField(
            model_name='statistics',
            name='stat_title2',
            field=models.CharField(default='Explore unreached people', max_length=255),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subtitle',
            field=models.CharField(default='Church Impact', max_length=255),
        ),
        migrations.AddField(
            model_name='statistics',
            name='title',
            field=models.CharField(default='Reaching Lives Across The Country', max_length=255),
        ),
    ]
