# Generated by Django 5.1.3 on 2024-12-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_statistics_stat_desc1_statistics_stat_desc2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistics Section', 'verbose_name_plural': 'Statistics Sections'},
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='total_people',
            new_name='people_groups',
        ),
        migrations.AddField(
            model_name='statistics',
            name='active_missionaries',
            field=models.IntegerField(default=0, help_text='Number of active missionaries'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='bible_translations',
            field=models.IntegerField(default=0, help_text='Number of Bible translations'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='converts',
            field=models.IntegerField(default=0, help_text='Number of converts'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='film_attendees',
            field=models.IntegerField(default=0, help_text='Number of film showing attendees'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='total_population',
            field=models.IntegerField(default=0, help_text='Total estimated population'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='training_sessions',
            field=models.IntegerField(default=0, help_text='Number of training sessions conducted'),
        ),
    ]
