# Generated by Django 5.1.3 on 2024-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aboutministry_aboutpage_boardmember_challenge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutministry',
            options={'ordering': ['order'], 'verbose_name_plural': 'About Ministry'},
        ),
        migrations.AddField(
            model_name='aboutministry',
            name='image',
            field=models.ImageField(blank=True, help_text='Ministry Image', null=True, upload_to='about/min_img/'),
        ),
    ]
