# Generated by Django 5.1.3 on 2024-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_project_projectpage_alter_sitelogo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Give', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='volunteer/give/')),
                ('donation_link', models.URLField(help_text='Link to donation page')),
            ],
        ),
        migrations.CreateModel(
            name='GoTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Go-Teams', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='volunteer/teams/')),
                ('team_members', models.TextField(help_text='List of team members')),
                ('join_team_link', models.URLField(help_text='Link to join the team')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prayer Partners', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='volunteer/prayer/')),
                ('volunteer_link', models.URLField(help_text='Link to volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='VOLUNTEER', max_length=200)),
                ('header_image', models.ImageField(help_text='Header image', upload_to='volunteer/')),
                ('introduction', models.TextField()),
            ],
            options={
                'verbose_name': 'Volunteer Page',
                'verbose_name_plural': 'Volunteer Page',
            },
        ),
    ]
