# Generated by Django 5.1.3 on 2024-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_givesection_goteam_prayerpartner_volunteerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('area_of_interest', models.CharField(choices=[('go_team', 'Go-Team Member'), ('prayer', 'Prayer Partner'), ('medical', 'Medical Outreach'), ('education', 'Education Support'), ('community', 'Community Development'), ('other', 'Other')], max_length=50)),
                ('skills', models.TextField(help_text='Please list your relevant skills and experience')),
                ('availability', models.TextField(help_text='When are you available to volunteer?')),
                ('message', models.TextField(blank=True, help_text='Additional message or questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='givesection',
            name='donation_link',
        ),
        migrations.RemoveField(
            model_name='goteam',
            name='join_team_link',
        ),
        migrations.RemoveField(
            model_name='goteam',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='prayerpartner',
            name='volunteer_link',
        ),
    ]
