# Generated by Django 5.1.3 on 2024-12-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bankaccount_bank_name_alter_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='christian_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Christian Population'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='converts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='film_attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='L.G.A'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='muslim_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Muslim Population'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='people_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='practiced_religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='total_village_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Village Population'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='traditional_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Traditional People Population'),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
